package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : AggregateEvent.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class AggregateEvent extends Event {

}
