package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : AggregateLine.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class AggregateLine extends EventLine {
    
	public Object eventReferenceLineCollection;
        
	public AggregateLine(StorageType storageType)
        {
            super(storageType);
        }
	public void CreateAggregateFromIterators() {
	
	}
	
	public void GetIteratorByTypeAndRange() {
	
	}
	
	public void AddEventByTypeAtPosition() {
	
	}
	
	public void EventLineExists() {
	
	}
	
	public void CreateEventLine() {
	
	}
}
