package musicgen;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : EventCollection.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class EventCollection {
	public Object list;
	public Object array;
	public Object tree;
        
	public void Insert(Event e) {
	
	}
	
	public void Delete() {
	
	}
	
	public void GetNext() {
	
	}
	
	public void GetPrevious() {
	
	}
}
