package musicgen;

//

import java.util.HashMap;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : Event.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//


public class Event {
    
    protected EventNode containingNode;
    protected String eventTypeName;        
    private HashMap <String, Event> referenceMap;
        
    public void AddReferenceToEvent(Event e) {
          
        String eventType = e.GetEventType();
        referenceMap.put(eventType, e);            
    }       
	
    public void Create() {
	
    }	

    public void Set() {

    }
	
    public void Get() {
	
    }
    
    public EventNode GetContainingNode(){

        return this.containingNode;
    }
    
    public void SetContainingNode(EventNode containingNode){

        this.containingNode = containingNode;
    }
    public String GetEventType() {
       
        return eventTypeName;	
    }
}
