package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : EventLine.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class EventLine extends Line {
    
	public EventLine(StorageType storageType) {
            
            super(storageType);
	}
	
	public void AddEventAtPosition(Event e, PositionType positionType) {

            if((positionType == PositionType.BEGINNING )||
                    (positionType == PositionType.END))
            {
                Insert(e, null, positionType);
            }
            else
            {
                //error.
            }
	}
	
	public void GetEventIterator() {
	
	}
	
	public void GetEventInAggregate() {
	
	}
}
