package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : EventLine.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class EventLine extends Line {
    
	public EventLine(StorageType storageType) {
            
            super(storageType);
	}
	
	public void AddEventAtPosition(Event e, PositionType positionType) {
            Insert(e, null, positionType);
	}
	
	public void GetEventIterator() {
	
	}
	
	public void GetEventInAggregate() {
	
	}
}
