package musicgen;

//

import java.util.Map;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : EventReferenceMap.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class EventReferenceMap {
    
    private Map <String, Event> map;
    
    public void AddReference(Event e) {
        String eventLineName = e.containingNode.GetEventLine().GetLineName();
        String eventType = e.GetEventType();
        String eventLineType = eventLineName + "-" + eventType;
      
        map.put(eventLineType, e);      
    }
    
//    public void AddReferenceByType(Event e) {

    public void HashValue() {

    }
}
