package musicgen;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : EventCollection.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//

import java.util.ArrayList;
import java.util.TreeSet;



public class EventCollection  {
    
    private StorageInterface storage;
    private StorageType storageType;
    
    public EventCollection(StorageType storageType) {
        this.storageType = storageType;
        switch (this.storageType)
        {
            case ARRAYLIST:
                storage = new ArrayListStorage();
                break;
            case TREESET:
                storage = new TreeSetStorage();
                break;
        }
    }
    
    public void InsertRelative(Event insertEvent, Event relativeEvent, 
            PositionType positionType) {
        
        storage.InsertRelative(insertEvent, relativeEvent, positionType);
    }
    
    public void InsertIrrelative(Event insertEvent, PositionType positionType) {
        
        storage.InsertIrrelative(insertEvent, positionType);
    }
    
    public void Delete(Event e) {
        storage.Delete(e);
    }
	
    public Event GetNext(Event e) {
        
        return storage.GetNext(e);	
    }
	
    public Event GetPrevious(Event e) {
        
        return storage.GetPrevious(e);		
    }
        
    public void ChangeStorageType(){
            
    }
}
