package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : EventReferenceLine.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class EventReferenceLine extends Line {
	public Object eventReferenceCollection;
        
        public EventReferenceLine(StorageType storageType)
        {
            super(storageType);
        }
}
