package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : EventLine.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class EventLine extends Line {
	public void EventLine() {
	
	}
	
	public void AddEventAtPosition() {
	
	}
	
	public void GetEventIterator() {
	
	}
	
	public void GetEventInAggregate() {
	
	}
}
