package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : Line.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class Line {
	private EventCollection eventCollection;
        
        public Line(StorageType storageType){
            
            eventCollection = new EventCollection(storageType);
        }
        
	public void Insert(Event insertEvent, Event relativeEvent, 
            PositionType positionType) {
            
            eventCollection.Insert(insertEvent, relativeEvent, positionType);
	}
	
	public void Delete(Event e) {
            eventCollection.Delete(e);
	}
	
	public void GetNext(Event e) {
            eventCollection.GetNext(e);	
	}
	
	public void GetPrevious(Event e) {
            eventCollection.GetPrevious(e);
	}
}
