package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : NoteEvent.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//

public class NoteEvent extends TypedEvent {

    private Pitch pitch;
//    //public enum PitchType { FREQUENCY, MIDINOTE, SCALEDEGREE, HARMONICDEGREE };
//    private int value;
//    private PitchType pitchType;
//            
//    
    
    public NoteEvent(Pitch pitch)
    {
        this.pitch = pitch;    
    }
    
}
