package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : OtherEvent.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class OtherEvent extends Event {
	public Object eventType;
}
