package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : Pitch.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//

public class Pitch {
    
    private double value;
    private PitchType pitchType;
    
        public Pitch(double initialValue, PitchType pitchType)
        {
            this.value = initialValue;
            this.pitchType = pitchType;    
        }
        
        public double FrequencyToMidi(double frequency)
        {
            double midiValue = 0.0;
            
            
            
            return midiValue;
        }
        
	public double GetMIDIValue() {
	
            double midiValue = 0.0;
            
            switch (pitchType)
            {
                case MIDINOTE:
                    midiValue = value;
                    break;
                    
                case FREQUENCY:
                    break;
                    
                case SCALEDEGREE:
                    break;
                    
                case CHORDDEGREE:
                    break;
            }
            
            return midiValue;
        }
	
	public void GetFrequencyValue() {
	
	}
	
	public void GetScaleDegree() {
	
	}
}
