package musicgen;
import java.lang.Math;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : Pitch.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//

public class Pitch {
    
    private double value;
    private PitchType pitchType;
    
        public Pitch(double initialValue, PitchType pitchType)
        {
            this.value = initialValue;
            this.pitchType = pitchType;    
        }
        
        public String toString()
        {
            return (String.valueOf(value) + " " +  String.valueOf(pitchType));
        }
        
        public double FrequencyToMidi(double frequency)
        {
            double midiValue = 0.0;
            double x = frequency/440;
            double logBase2_of_X = Math.log(x) / Math.log(2);
                    
            midiValue = 12* logBase2_of_X + 69;           
            
            return midiValue;
        }
        
        public double MidiToFrequency(double midiValue)
        {
            double frequency = 0.0;            
            double distanceFromA440 = midiValue - 69;            
            
            frequency = Math.pow(2, distanceFromA440/ 12) * (440);

            return frequency;
        }
	public double GetMIDIValue() {
	
            double midiValue = 0.0;
            
            switch (pitchType)
            {
                case MIDINOTE:
                    midiValue = value;
                    break;
                    
                case FREQUENCY:
                    midiValue = FrequencyToMidi(value);
                    break;
            }
            
            return midiValue;
        }
	
	public double GetFrequencyValue() {
            
            double frequency = 0.0;
            switch (pitchType)
            {
                case FREQUENCY:
                    frequency = value;
                    break;
                    
                case MIDINOTE:
                    frequency = MidiToFrequency(value);
                    break;
            }
            
            return frequency;
        }
	
	public void GetScaleDegree() {
	
	}
}
