package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : ReferenceEvent.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class ReferenceEvent extends Event {
	public Object eventReference;
	public void SetToEvent() {
	
	}
}
