package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : TextureEvent.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class TextureEvent extends TypedEvent {
}
