package musicgen;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : MusicGen
//  @ File Name : TypedEvent.java
//  @ Date : 6/24/2014
//  @ Author : Phil
//
//




public class TypedEvent extends Event {
	public Object aggregateEventReference;
}
