//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AggregateEvent.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class AggregateEvent extends Event {
	public Object eventReferenceMap;
	public void AddReferenceToEvent() {
	
	}
}
