//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AggregateLine.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class AggregateLine extends Line {
	public Object eventReferenceLineCollection;
	public void AggregateLine() {
	
	}
	
	public void CreateAggregateFromIterators() {
	
	}
	
	public void GetIteratorByTypeAndRange() {
	
	}
	
	public void AddEventByTypeAtPosition() {
	
	}
	
	public void EventLineExists() {
	
	}
	
	public void CreateEventLine() {
	
	}
}
