//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Event.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class Event {
	public Object eventTypeName;
	public void Create() {
	
	}
	
	public void Set() {
	
	}
	
	public void Get() {
	
	}
	
	public void GetEventType() {
	
	}
}
