//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EventReferenceLine.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class EventReferenceLine extends Line {
	public Object eventReferenceCollection;
}
