//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EventReferenceMap.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class EventReferenceMap {
	public void AddReferenceByType() {
	
	}
	
	public void HashValue() {
	
	}
}
