//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EventCollection.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class EventCollection {
	public Object list;
	public Object array;
	public Object tree;
	public void Insert() {
	
	}
	
	public void Delete() {
	
	}
	
	public void GetNext() {
	
	}
	
	public void GetPrevious() {
	
	}
}
