//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EventIterator.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class EventIterator {
	public Object currentEvent;
	public void CreateEventAtPosition() {
	
	}
	
	public void GetNextEvent() {
	
	}
	
	public void GetPreviousEvent() {
	
	}
}
