//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HarmonyEvent.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class HarmonyEvent extends TypedEvent {
}
