//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Line.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class Line {
	public Object eventCollection;
	public void Insert() {
	
	}
	
	public void Delete() {
	
	}
	
	public void GetNext() {
	
	}
	
	public void GetPrevious() {
	
	}
}
