//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OtherEvent.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class OtherEvent extends Event {
	public Object eventType;
}
