//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pitch.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class Pitch {
	public void GetMIDIValue() {
	
	}
	
	public void GetFrequencyValue() {
	
	}
	
	public void GetScaleDegree() {
	
	}
}
