//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReferenceEvent.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class ReferenceEvent extends Event {
	public Object eventReference;
	public void SetToEvent() {
	
	}
}
