//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StyleEvent.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class StyleEvent extends TypedEvent {
}
