//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TextureEvent.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class TextureEvent extends TypedEvent {
}
