//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TimeEvent.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class TimeEvent extends TypedEvent {
}
