//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TypedEvent.java
//  @ Date : 6/24/2014
//  @ Author : 
//
//




public class TypedEvent extends Event {
	public Object aggregateEventReference;
}
